version: "3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - db
    env_file:
      - .env
  db:
    image: mongo:5
